# Generated by Django 2.2.11 on 2020-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
                ('cover_img', models.ImageField(upload_to='images/')),
                ('discription', models.CharField(max_length=2000)),
                ('education', models.CharField(max_length=2000)),
                ('experience', models.CharField(max_length=2000)),
            ],
        ),
    ]
