# Generated by Django 2.2.11 on 2020-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200501_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name=''),
        ),
    ]
